### ISSUE TITLE
Migration of the Phyphox source code from GitHub to Codeberg

### ISSUE THREAD

**Issue by Lukas2112** [phyphox/phyphox-android#25]
GitHub has belonged to the US technology group Microsoft since 2018. In a way, this goes hand in hand with a kind of dependency relationship of the project on Microsoft. 

Codeberg is a FLOSS alternative to GitHub based on Gitea. The servers are operated within the EU (Germany). 

Besides the fact that GitHub now belongs to Microsoft (for a long time), would there be other dependencies that would stand in the way of a switch from GitHub to Codeberg?

**Comment by Staacks** [comment]
While I really appreciate FLOSS platforms over closed systems, I do not see an immediate problem in hosting the project on a Microsoft-owned service. I also do not see a "kind of dependency relationship" as this is not the only copy of the source code and it's published under a public licence anyways. In fact, if Microsoft decided to shut down github tomorrow or somehow use it for evil, we could be on the next platform the day after that and the only downside would be that it breaks the URLs to the repository and any forks. Which is something that also happens if we move right now.

The advantage of github is that it is an established platform that is familiar to pretty much any developer out there, so it helps in terms of exposure and accessibility for possible collaborators and projects that want to use our source.

So, although I really appreciate your project and at least see a slight problem in using the US corporate platform over the EU non-profit alternative, I do not think that moving would be in the interest of phyphox at this point.
