### ISSUE TITLE
Add light theme

### ISSUE THREAD

**Issue by xmha97** [phyphox/phyphox-android#26]
Hi, thanks for this app.
Please add light theme.

**Comment by Staacks** [comment]
I have put this on my todo list to think about it. The problem here is that this might be problematic in some edge cases with custom experiment configurations where the user defined a font color and/or separator color which is not from our default color palette. I think that we could work around this and that it would not be too much work, but since it still is "some" work and since the dark color scheme has become something quite recognizable, I am wondering why you need this?

In my experience a missing dark theme is much more problematic except for presentation on projectors. The remote access actually got a light mode for this reason. So, what is your use case, so we can understand it?

**Comment by xmha97** [comment]
Thanks for your explanation but all the apps I installed have both a dark theme and a light theme.
I always use the light theme because I'm more comfortable with it.

**Comment by Staacks** [comment]
ok, that's low priority then, but I can see how it would be nice if it was consistent with the behavior of the OS and other apps.

**Comment by xmha97** [comment]
After adding the light theme, it would be great if this feature was also added:
- Sync app theme with OS theme.
![Screenshot_2022-01-05-20-09-16-921_org.mozilla.firefox_1_1.jpg](https://user-images.githubusercontent.com/23485114/148255054-c60d003e-58d2-48cf-8329-61079f8515ee.jpg)

**Comment by lgommans** [comment]
I hadn't really identified phyphox as having a "dark theme". I guess the theme has the property of being dark by nature, but to me it's just phyphox' own custom look as it is. Personally, I wouldn't need a special bright background color for any reason. Sometimes in direct sunlight a light theme can help (my old Huawei LCD would increase screen contrast when the backlight was already at the max and the sensor told it there was still more light, and that did help), but I haven't had the issue with phyphox that something was hard to read under any condition.

**Comment by Staacks** [comment]
Thanks. The main reason we keep this on our todo list is the use in schools. Not because of readability on screen (although that can be an issue if the phyphox interface is streamed to a projector) but on a print-out. Worksheets are often handed out as a print-out and students tend to document their work with a screenshot from the app in a similar way. Here a light version would be quite helpful.

**Comment by xmha97** [comment]
Thanks for adding the light theme.


Please set the "System" as default theme.

**Comment by Staacks** [comment]
> Please set the "System" as default theme.

There are several reasons that we did not set this as the default:
- The "orange on dark" look is very recognizable as a phyphox trademark and we have been using this in many locations where you cannot switch between dark or bright mode (i.e. print media, posters, videos etc.)
- We try to avoid interface changes when not necessary to not confuse or interrupt classes. While these are just colors, setting dark as default allows students and teachers to use the new version without even noticing the new option if they do not care about it.
- A unified default look (i.e. independent of system settings) makes it easier for teachers to provide material that matches the look that the students have on their phones. I have to admit that this is a rather weak argument as we already ignore this in case of common design patterns in Android vs. iOS, but if there is no reason to add different looks, we would avoid different looks for freshly installed versions.
- Some experiments (like evaluating the inverse square law with the light sensor) work significantly better without light spill from a bright screen. Defaulting to the dark version removes one setup step (in a somewhat hidden menu for advanced options) that needs to be instructed in class.

So, why do you care about the default when you can set it to your personal preference? Anyone who cares can easily set it, but for most users who do not care, the dark theme is the better option.
