### ISSUE TITLE
Complex.experiments please

### ISSUE THREAD

**Issue by Noitarud** [phyphox/phyphox-android#29]
I notice you have a tilt experiment but it is too slow - if only I could read two values from the accelerometer do the trig (perhaps write in as you would in a spreadsheet) and see the result!
If you think that was a hint to speed it up, that was not all, I see this has two accelerometers, perhaps I can ask to select which (that will let me see if they are in different places, else its just a duplicate. the one selected is near the left speaker). If different, can then do some investigation on a hinge to discover the gap and I can find rotation rate (as if a gyro, maybe not, only axis location, maybe infer gyro cumulatively). And can get fancy and do 3D mapping. Not to be confused with tilt rotation rate, another complex one. (Nb. my enthusiasm to do all that is low, stating possibilities)

(For that matter, allow us to select from any sensor, eg the step counter, maybe we can do our own calibration ax+b)
Of course complex experiments will enable the community to broaden the portfolio of PPs experiments.

**Comment by Staacks** [comment]
Not sure if I understand this completely, but I think there are two aspects to this:

a) Clarification on the sensors
With "two accelerometers" you are probably refering to "acceleration with g" and "acceleration without g". The latter, however, is just a virtual sensor based on the data from the one "with g". Here, Earth's acceleration is subtracted, which is why you could not derive the device's orientation from this anyway. In fact, the device needs to determine its orientation in order to be able to subtract g. It depends on the manufacturer's implementation how this is done, but in most cases the phone fuses the data from the actual accelerometer (the one "with g"), the gyroscope and sometime also the magnetometer to derive "acceleration without g". Also, the "step counter" does not allow low level access to another accelerometer. It is an interface to allow apps to access the "step count" without keeping the device awake as they try to do this themselves by reading the accelerometer. The actual implementation again depends on the device, but to my understanding nowadays it is usually done with a dedicated coprocessor that does the read-outs and accumulation with as little power requirements as possible.

b) You can already configure complex experiments in phyphox
Every entry in the main menu of phyphox is not hardcoded but based on our own file format. You can change pretty much anything about any experiment or write your own experiments. Each entry is just an XML file that can be either send to the phone conventionally (email, messengers, cloud storage etc.) or via an QR code (recommended when sharing with students). With this format, you can select data sources (sensors, Bluetooth, network, microphone, GPS etc.), data outputs (speaker, Bluetooth, network), visualizations (graphs, simple values, buttons, edit fields, text etc.) and connect them with "analysis" modules ranging from basic arithmetic to more advanced things like Fourier transforms or cross-correlation. You can find some examples from other users in our forums or get an idea of what the format can do with some of our event experiments like https://phyphox.org/piday/ or https://phyphox.org/xmas/. The documentation for the format can be found in our Wiki: https://phyphox.org/wiki/index.php/Phyphox_file_format

**Comment by Noitarud** [comment]
Hello, I thought to inspire you a little, here are two more sensors that
can be used:

•battery has a thermometer, obviously will lag due to thermal mass and
battery has tolerance limits (unless extracted) but it is another sensor…

•battery system has a current sensor, you should be able to measure current
drawn (above quiescent) by a device connected on an OTG cable to the USB
port. may need to calibrate for variables such as backlight intensity and
discover disruptive functions and apps.


Charlie.

**Comment by Staacks** [comment]
Thanks for the inspiration. The problem with both suggestions is that the energy management of the phone is very complex. The current draw is influenced by wake/sleep cycles and clock changes of the CPU, the use of GPU, the usage of all radio devices (Wifi, Bluetooth, mobile data), display brightness and additional components like GPS, speakers, sensors and sometimes supporting processors (for example for step counter functionality without bothering the main CPU with it).

While some of them can be controlled or change rarely, most of these are significant and cannot even be observed on an app level. As you mention, we have no control over wake/sleep cycles of other apps or even the system's sync and heartbeat behavior. But the worst here are certainly the radio devices as they constantly switch between massive current draw while sending and near zero power saving states, which is all controlled by OS and firmware without any way to control or even observe the behavior as an app. On top of it all, their power requirements change with signal strength and different standards of the existing infrastructure (4g vs. 3g vs. old GSM, 5 Ghz Wifi vs. 2.4 Ghz and all their different standards).

This makes the current draw from the battery unpredictable and limits this concept to long-term averages and a rough estimate at best.

This also indirectly affects the temperature sensor problem. From a physics point of view, this is one of the worst temperature probes to begin with as it comes with a very high heat capacity (in contrast to the small tip of a thermometer which quickly adapts to external temperatures) and no proper thermal contacts. Even worse, the battery only has a temperature sensor because it heats up on its own while in use and it is either not thermally connected to anything (in which case the self-heating would dominate anything) or it is thermally connected to the phone's body for heat dissipation (not sure if this is common), in which case it is affected by the heat from other components like the CPU, too.

Phyphox actually is already able to read temperature sensors that register themselves as TYPE_AMBIENT_TEMPERATURE and it even tries to expose vendor-specific temperature sensors that give themselves away by having "temperature" or "thermo" in their name. You can access these by creating a "Simple experiment" via the "+" button in the main menu. But we do not list them among the other sensor types, because we do not think that any of them are suitable for experiments in STEM education (which is our main purpose).

The ones identified by their name are nearly unusable as a temperature probe. These are typically sensors that are part of another sensor like the barometer and only intended to calibrate this particular sensor. Therefore they do not necessarily need to give the temperature outside the phone as long as they match the temperature required to calibrate the sensor. For example, for a barometer it just needs to represent the temperature of the air inside the phone at the sensor.

The ones that register as TYPE_AMBIENT_TEMPERATURE are sensors that are intended to measure the temperature and therefore slightly better. However, looking at the way a phone is constructed, it is nearly impossible to give them a proper thermal contact to the outside and to insulate it from the heat that the phone generates itself. It seems like those manufacturers that even offer these sensors (very few models) try to estimate the internal heat and account for it, but we are not convinced that this can be done in any meaningful way that could be used in an experiment.

So, phyphox already offers these two temperature sensor types with some "skeptical reluctance" and the battery is certainly worse than these two. It is buried deeper in the system and there to monitor the self-heating. While I agree that is still interesting to monitor these types of parameters, we do not want to overload phyphox with these as they are technical parameters and not something that can be used for experimentation in science class.

**Comment by Noitarud** [comment]
I am using a tablet and can switch the radios off ; )  (and yes I know it also transmits without user authorisation, such as for big brother's sake, so would have to pull the antennae off) and the results would show impact of user input too. Yes, a wise idea would be to blank screen while sampling is in progress for less noise in the result. My application was to see the current usage of various things, USB fan…. this would save time if in this. I am not sure if it has an overload protect… so reccomend a maximum mark on the chart.

As for the thermal load, I knew, but the idea was to see the effect of leaving the tablet in the car, I may as well record how it fairs while it is there. The battery sensor is more sensible to see aging potential, but I cannot think of uses for these others you mention.
