### ISSUE TITLE
Update readme for using requests to get realtime sensor data.

### ISSUE THREAD

**Issue by ftune** [phyphox/phyphox-android#33]
The web page will be of help to download data. But I can't get the realtime data which might be useful when designing the real time footstep counter or gym counter.
I learned by inspector in Firefox that the web page is using get method for accX accY accZ after the monitor start. But there is no readme for how to use requests to get and read the batch data or time series.
```http://192.168.106.129:8080/get?accX=0.77274132|acc_time&acc_time=0.77274132&accY=0.77274132|acc_time&accZ=0.77274132|acc_time```

**Comment by Staacks** [comment]
Since the apps are spread across four repositories (phyphox-android, phyphox-ios and then phyphox-experiments and phyphox-webinterface as submodules for both), the documentation is in our wiki: https://phyphox.org/wiki

You are specifically looking for https://phyphox.org/wiki/index.php/Remote-interface_communication

I will add a link to the wiki to the readme.
