### ISSUE TITLE
Truth edge-indicators

### ISSUE THREAD

**Issue by Noitarud** [phyphox/phyphox-android#56]
This is slightly related to #55, have edge lighting to signal certain states, experimenter can place sensors on the front of the screen to respond to the sensor readings.

- Will need to make characteristic signals so machine phone is attached to doesn't respond to the app being swapped out.
- low bitrate communication (to send readings to external devices, action may appear like teletext bars did).
- Allow filling of screen, maybe you have to view it with binoculars.
- I read LEDs are sensitive and generate a response to applied light(presume certain wavelengths, make voltage from light or alter loading), perhaps could use RGB cluster on a zone and zone can emit in colour.
- Could the GPS do lines 1-2m apart for crop planting?

**Comment by Staacks** [comment]
If I understand this correctly, you want a machine-readable state on the screen? While this is an interesting concept, is there any use-case that is not covered by Wifi or Bluetooth?

**Comment by Noitarud** [comment]
That is right.
I can avoid the need for accessories and just use transistors and probably LEDs to acquire thresholds from device. The data feature is the only overlap except when radio silence is required (some people consider/demand radioless to have a healthier lifestyle, look up terms such as "dirty electricity" or "electrosensitive").

I am not going to push hard for this since I am not developing, only making sure the idea is known.

Example signals:
•maybe can blip when a whole [degree is turned]
•on when over thresholds
•on when over rate of change
•blip for elapsed time
•on when FFT place reaches intensity
Can "AND" the above with external circuitry, but I do ask for Off for the above (as well) since that favours the way I design circuits (I use PNPs and NPNs to switch top and bottom of channel for an AND).

**Comment by Staacks** [comment]
Just to clarify: The Wifi solution does not need additional hardware, except a second device from which you want to control/read the experiment - but you would also need a device to read the optical indicators. The [remote access](https://phyphox.org/remote-control/) feature of phyphox does not require any infrastructure and especially no internet connection is required. The phone can act as a hotspot and any other device can connect to it.

This pretty much leaves the users that are worried about radio signals, but I doubt that those would pick a smartphone as a measurement device to begin with.

By the way, an interesting aspect of your suggestion could be that notifications of thresholds could be perceived without looking at the screen by using acoustic signals. This is already possible with phyphox! Our [XML format for custom experiments](https://phyphox.org/wiki/index.php/Phyphox_file_format) let's you analyse the sensor data (a threshold would just be the beginning) and allows you to control the tone generator depending on the result of the analysis. The problem at the moment is that our XML format is rather complex, but hopefully we will publish our new web editor for this format soon.

I will close this issue now, because it is something we will quite certainly not implement (please also take into account that our focus is the use case in science education). However, if you have a specific use case where you need an acoustic signal base on sensor data, please let me know and I will set up a matching configuration for you.

**Comment by Noitarud** [comment]
As written at start, LEDs are sensitive to incident light (they might generate like a solar panel but reverse (generation to resist applied flow) would probably be more effective) you can use those to switch transistors on and off, LDRs are a more customary sensor, harder to scavange.

Some technologies are worse than others. It might be a case of acclimatisation, I don't notice 2.4 WiFi but notice a number of others. Such awareness allows you to notice things that you were not supposed to notice, such as the multimedia box hacking into the router and modifying its firmware (both from the network providor, that would be a Trojan horse attack).

Sound can work, and use headphones, yes, volume will be easy enough, frequency would be more complex, binary codes would require registers…
Alright, if "no" then no it is.

**Comment by Staacks** [comment]
It's not "no" in the sense that a visual feedback for readings may not be in phyphox - if someone implements it in a way that does not interfere with normal use in schools, I will happily merge it into the production version of phyphox. But it is "no" in the sense that we will not implement it ourselves as there are many things to implement that are more relevant to teaching.
