### ISSUE TITLE
Exporting audio spectrum history data

### ISSUE THREAD

**Issue by IskraAI** [phyphox/phyphox-android#62]
Greetings,

I noticed that one cannot export "History" data (spectrogram) from "Audio Spectrum" tool. That would be a great feature and was missing while i worked with students on an acoustic project. I hope I am not missing something and I also hope this is the right place to report such "findings" (new to GitHub).

**Comment by Staacks** [comment]
Indeed, the spectrogram is not included in the export data set. I have to think about whether we should include it or not because it is a but "unwieldy" as it is >32000 rows of data triplets and you can export it directly if you need to: Tap the history data plot, select "More tools" in the bottom left corner and then select "Export this dataset". In contrast to the export function in the top-right menu, this export function always exports exactly the data from the graph, allowing to export particular datasets that we do not export by default and allowing for exporting CSV data without a zip container (helpful to directly send data to other apps).

(I'll close this now as the feature is basically already available, but please let me know if this works for you and of course in particular if it does not solve your issue.)

**Comment by IskraAI** [comment]
Staacks, thank you for very detailed and insightful answer. I did not realize, that the "Export this dataset" option in "More tools" returns History dataset. This completely solves my issue. Have a nice day!
