### ISSUE TITLE
Doppler effect auto configure

### ISSUE THREAD

**Issue by Noitarud** [phyphox/phyphox-android#66]
Suppose someone is on a motorcycle about to go past.
The app could record this, and, without configuration, could obtain the frequency at pitch inversion and then show the relative speed from when it was first heard until fade, graph can begin to be presented after inversion (updated) or after fade (complete).

The user could be allowed to tap at around inversion so app knows which inversion was of interest (or show each one - can tell instantaneous gains between racers).

**Comment by Staacks** [comment]
_First of all, thanks for all your input. I have seen a few from you pop up in my mail over the weekend and will now answer them all. However, please understand that I will be closing a few of them as this issue tracker (while not really well maintained to begin with) is more for issues (i.e. bugs, crashes, problems) and not that much about feature requests. We have a very long internal list of features that would be nice to have, but limited development capacities, so we usually decide based on how many users would benefit from something and the forums at https://phyphox.org/forums/ might be a much better place with more active users supporting a request or having additional input. I will also copy this block in italics to some of the issues that I close, so others who stumble upon them can read this, too._

Now, about this particular request: Do you have an implementation in mind? The "without configuration" part sounds great, but our current Doppler Effect version has all these configuration parameters because it is not exactly easy to determine a frequency shift at both a high spectral resolution and a high temporal resolution. For an unknown noise signal, I can only think of comparing Fourier transforms, which will not be able to achieve both resolutions simultaneously. So, if you have a specific method in mind (wavelet transforms?), please let us know as our knowledge in this area is a bit limited.

(Closing it as I do not see how this can be implemented at the moment. Feel free to answer with suggestions anyway.)
